"""Report every human-gold row where the human and the LLM ensemble disagree.

The gold subset is the only thing that says whether the ensemble's notion of
sarcasm matches yours.  When Cohen's kappa is low the aggregate number does not
tell you *which side* is off -- this prints each disagreement with the target,
the context the annotators actually saw, all three annotator rationales and the
adjudicator's, so the call can be made by reading rather than by arithmetic.

    uv run python tools/gold_disagreements.py [--label sarcastic] [--out report.md]

Rerun it whenever the gold subset grows.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LABELS = ("sarcastic", "language", "literal_sentiment", "intended_sentiment")


def load(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def cohen_kappa(pairs: list[tuple]) -> float | None:
    """Two-rater Cohen's kappa over whatever categories actually appear."""
    if not pairs:
        return None
    n = len(pairs)
    cats = sorted({v for pair in pairs for v in pair}, key=str)
    observed = sum(a == b for a, b in pairs) / n
    a_counts, b_counts = Counter(a for a, _ in pairs), Counter(b for _, b in pairs)
    expected = sum((a_counts[c] / n) * (b_counts[c] / n) for c in cats)
    return None if abs(1 - expected) < 1e-12 else (observed - expected) / (1 - expected)


def clip(text: object, n: int = 400) -> str:
    s = " ".join(str(text or "").split())
    return s[:n] + ("…" if len(s) > n else "")


def render(rows: list[dict], label: str) -> str:
    gold = [r for r in rows if r.get("human_gold")]
    out: list[str] = []
    w = out.append

    w(f"# Gold-vs-ensemble disagreements — `{label}`\n")
    w(f"Generated by `tools/gold_disagreements.py` over {len(gold)} human-labelled rows "
      f"(of {len(rows)} total).\n")

    # ---- the confusion the aggregate kappa is hiding
    values = sorted({r["human_gold"][label] for r in gold} | {r["labels"][label] for r in gold}, key=str)
    grid = Counter((r["human_gold"][label], r["labels"][label]) for r in gold)
    w("## Confusion — human (rows) × ensemble (columns)\n")
    w("| human \\ ensemble | " + " | ".join(f"`{v}`" for v in values) + " |")
    w("|---" * (len(values) + 1) + "|")
    for h in values:
        w(f"| **`{h}`** | " + " | ".join(str(grid[(h, e)]) for e in values) + " |")
    agree = sum(v for k, v in grid.items() if k[0] == k[1])
    kappa = cohen_kappa([(r["human_gold"][label], r["labels"][label]) for r in gold])
    majority = max(Counter(r["human_gold"][label] for r in gold).values())
    w("")
    w(f"- raw agreement **{agree}/{len(gold)} = {agree / len(gold):.1%}**")
    w(f"- Cohen's κ **{kappa:+.4f}**" if kappa is not None else "- Cohen's κ: undefined")
    w(f"- always predicting the majority class would score {majority / len(gold):.1%} — "
      "raw agreement below this bar means the ensemble is adding noise, not signal")
    w("")

    # ---- is the gold subset representative?
    w("## Is the gold subset representative?\n")
    w("κ on a small, deliberately hard sample is biased downward. How these rows compare "
      "to the corpus they were drawn from:\n")
    w("| | gold subset | full corpus |")
    w("|---|---|---|")
    for field, getter in (("resolved_by", lambda r: r["reliability"]["resolved_by"]),
                          ("sarcasm_votes", lambda r: r["reliability"]["sarcasm_votes"]),
                          ("language (ensemble)", lambda r: r["labels"]["language"])):
        g_ct, a_ct = Counter(map(getter, gold)), Counter(map(getter, rows))
        fmt = lambda ct, tot: ", ".join(f"{k} {v / tot:.0%}" for k, v in sorted(ct.items()))
        w(f"| {field} | {fmt(g_ct, len(gold))} | {fmt(a_ct, len(rows))} |")
    w("")

    # ---- every disagreement, in full
    bad = [r for r in gold if r["human_gold"][label] != r["labels"][label]]
    w(f"## The {len(bad)} disagreements\n")
    w("Read each one and decide: is the ensemble wrong, or was the manual pass applying a "
      "different threshold? Both answers are publishable. Not knowing is not.\n")

    for i, r in enumerate(bad, 1):
        rel, ctx = r["reliability"], r["context"]
        w("---\n")
        w(f"### {i}. `{r['reddit_fullname']}` — human **`{r['human_gold'][label]}`** "
          f"vs ensemble **`{r['labels'][label]}`**\n")
        w(f"*{r['subreddit']} · {r['record_type']} · depth {r.get('depth')} · "
          f"votes {rel['sarcasm_votes']} · resolved by {rel['resolved_by']}*\n")
        w(f"> **TARGET:** {clip(r['text'], 600)}\n")

        sub = ctx.get("submission")
        if sub:
            w(f"- **submission:** {clip(sub.get('title'))}")
            if sub.get("selftext"):
                w(f"  - *selftext:* {clip(sub['selftext'], 300)}")
        for j, p in enumerate(ctx.get("parent_chain") or []):
            w(f"- **parent {j}:** {clip(p.get('text'), 300)}")
        for j, rp in enumerate(ctx.get("replies") or []):
            w(f"- **reply {j}:** {clip(rp.get('text'), 300)}")
        if not sub and not ctx.get("parent_chain") and not ctx.get("replies"):
            w("- *(no conversational context)*")
        w("")

        w("| annotator | sarcastic | literal→intended | conf | rationale |")
        w("|---|---|---|---|---|")
        for a in rel.get("annotators") or []:
            w(f"| {a['model_key']} | {a['sarcastic']} | "
              f"{a['literal_sentiment']}→{a['intended_sentiment']} | "
              f"{a.get('confidence', float('nan')):.2f} | {clip(a.get('rationale'), 260)} |")
        adj = rel.get("adjudicator")
        if adj:
            w(f"| **{adj['model_key']}** (adj) | **{adj['sarcastic']}** | "
              f"{adj['literal_sentiment']}→{adj['intended_sentiment']} | "
              f"{adj.get('confidence', float('nan')):.2f} | {clip(adj.get('rationale'), 260)} |")
        hg = r["human_gold"]
        w(f"| **human** | **{hg['sarcastic']}** | "
          f"{hg['literal_sentiment']}→{hg['intended_sentiment']} | — | "
          f"{clip(hg.get('notes')) or '*(no note)*'} |")
        w("")

        cues = [k for k, v in (r["labels"].get("cues") or {}).items() if v]
        h_cues = [k for k, v in (hg.get("cues") or {}).items() if v]
        w(f"- cues — ensemble: {', '.join(cues) or 'none'} · human: {', '.join(h_cues) or 'none'}")
        tx = (r.get("aux") or {}).get("tx_sentiment") or {}
        if tx:
            w(f"- external sentiment (`{tx.get('model', '?')}`): **{tx.get('label')}** "
              f"(pos {tx.get('p_pos')} / neu {tx.get('p_neu')} / neg {tx.get('p_neg')})")
        w("")

    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dataset", default=None, help="path to dataset-*.jsonl")
    ap.add_argument("--label", default="sarcastic", choices=LABELS)
    ap.add_argument("--out", default=None, help="write markdown here instead of stdout")
    args = ap.parse_args()

    path = Path(args.dataset) if args.dataset else next(
        p for p in sorted((ROOT / "data").glob("dataset-*.jsonl"), reverse=True))
    rows = load(path)
    if not any(r.get("human_gold") for r in rows):
        raise SystemExit(f"{path.name} carries no human_gold rows — nothing to compare")

    report = render(rows, args.label)
    if args.out:
        Path(args.out).write_text(report, encoding="utf-8")
        print(f"wrote {args.out}")
    else:
        print(report)


if __name__ == "__main__":
    main()
